services:
    app:
        container_name: syntharena-app
        build: .
        ports:
            - '1000:3000'
        env_file: .env
        environment:
            - DATABASE_URL=file:/app/data/prod.db
        volumes:
            - ./production_data:/app/data
        restart: unless-stopped
